# Tarea 5:

## Comparación de Algoritmos de Clasificación

En esta tarea consiste en hacer una comparación de los clasificadores visto hasta ahora:

- Naives Bayes
- Perceptrón
- Regresión Logística
- k-Vecinos más Cercanos
- Árboles de Decisión
- SVM
- Random Forrest
- AdaBoost

Usando un conjunto de datos de enfermedades cardíacas, el cual incluye más de 4240 registros, 16 columnas y 15 atributos. El objetivo del conjunto de datos es predecir si el paciente tiene riesgo de sufrir una enfermedad coronaria en los próximos 10 años (TenYearCHD)

Puntos a desarrollar:
- Dividir los datos con un 20% de los datos para pruebas 
- Convertir datos categóricos a numéricos.
- Normalizar los atributos.
- Realizar visualizaciones de los datos.
- Para cada algoritmo que tenga hiperparámetros, hacer una búsqueda de los mejores valores usando validación cruzada.
- Graficar las regiones de decisiones para cada uno de los algoritmos.
- Generar una tabla ordenada por el rendimiento sobre el conjunto de prueba, que muestre la exactitud de entrenamiento, exactitud de prueba y el tiempo de ejecución.
- Mostrar la matriz de confusión y la curva ROC para cada clasificador

La fecha límite de entrega de la tarea es el día 4 de Agosto antes de la clase.

In [3]:
import pandas as pd
wisc = pd.read_csv('../datos/cardiovascular.csv')
wisc.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0